package com.example.domain.repository.todo;

import com.example.domain.model.todo.Todo;
import com.example.domain.model.todo.TodoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TodoRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    long countByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    int deleteByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String todoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    int insert(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    int insertSelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    List<Todo> selectByExampleWithRowbounds(TodoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    List<Todo> selectByExample(TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    Todo selectByPrimaryKey(String todoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Todo record, @Param("example") TodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Todo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Todo record);
}