package com.example.domain.model.todo;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Database Table Remarks:
 *   Todo
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.todo
 */
@Data
public class Todo implements Serializable {
    /**
     * Database Column Remarks:
     *   Todo内部番号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.todo.todo_id
     *
     * @mbg.generated
     */
    private String todoId;

    /**
     * Database Column Remarks:
     *   Todoタイトル
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.todo.todo_title
     *
     * @mbg.generated
     */
    private String todoTitle;

    /**
     * Database Column Remarks:
     *   完了フラグ
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.todo.finished
     *
     * @mbg.generated
     */
    private Boolean finished;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.todo.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.todo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}